// SPA/spa-router-apps/react-spa-app/src/routes/Contact.jsx

import React, { useState } from 'react'

export default function Contact() {
  const [name, setName] = useState('')
  const [message, setMessage] = useState('')
  const [submitted, setSubmitted] = useState(false)

  const handleSubmit = (e) => {
    e.preventDefault()
    setSubmitted(true)
  }

  return (
    <section>
      <h2>Kontakt</h2>
      <form onSubmit={handleSubmit}>
        <label>
          Imię:
          <input value={name} onChange={(e) => setName(e.target.value)} required />
        </label>
        <label>
          Wiadomość:
          <textarea value={message} onChange={(e) => setMessage(e.target.value)} required />
        </label>
        <button type="submit">Wyślij</button>
      </form>
      {submitted && <p>Dziękujemy za wiadomość, {name}!</p>}
    </section>
  )
}

// SPA/spa-router-apps/angular-spa-app/src/app/pages/contact.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';

@Component({
  standalone: true,
  imports: [FormsModule, CommonModule],
  selector: 'app-contact',
  template: `
    <h2>Kontakt</h2>
    <form (ngSubmit)="submitForm()">
      <label>Imię: <input [(ngModel)]="name" name="name" required /></label>
      <label>Wiadomość: <textarea [(ngModel)]="message" name="message" required></textarea></label>
      <button type="submit">Wyślij</button>
    </form>
    <p *ngIf="submitted">Dziękujemy, {{ name }}!</p>
  `,
  styleUrls: ['./contact.component.css']
})
export class ContactComponent {
  name = '';
  message = '';
  submitted = false;

  submitForm() {
    this.submitted = true;
  }
}
