// SPA/cats-frameworks-apps/vue-cat-app/src/App.vue
<template>
  <v-app>
  <NavBar @mode-change="showFavorites = $event" />
  <v-main>
  <v-container fluid>
    <FavouritesFeed v-if="showFavorites" />
    <RandomFeed v-else /> 
  </v-container>
</v-main>
</v-app>
</template>

<script setup>

import { ref } from 'vue'
import NavBar from './components/NavBar.vue'
import FavouritesFeed from './components/FavouritesFeed.vue'
import RandomFeed from './components/RandomFeed.vue'

const showFavorites = ref(false)
</script>

<style scoped>
/* Przenieś tu zawartość z App.css, jeśli potrzebna */
</style>

// SPA/cats-frameworks-apps/react-cat-app/src/App.jsx
import { Box } from '@mui/material';
import { useState } from 'react';
import './App.css';
import FavouritesFeed from './components/FavouritesFeed';
import NavBar from './components/NavBar';
import Feed from './components/RandomFeed';

function App() {

  const [showFavorites, setShowFavorites] = useState(false);

  return (
    <Box>
      <NavBar onModeChange={setShowFavorites}></NavBar>
      {!!showFavorites? <FavouritesFeed/> : <Feed></Feed>}
      </Box>)
}

export default App;
