// SPA/spa-router-apps/react-spa-app/src/App.jsx
import React, { Suspense, useState } from 'react'
import { NavLink, Routes, Route } from 'react-router-dom'

const Home = React.lazy(() => import('./routes/Home'))
const About = React.lazy(() => import('./routes/About'))
const Contact = React.lazy(() => import('./routes/Contact'))

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false)

  return (
    <div id="app">
      <header>
        <nav className="navbar">
          <div className="logo">🌐 Moja SPA</div>
          <button className="hamburger" onClick={() => setMenuOpen(!menuOpen)}>
            ☰
          </button>
          <ul className={`nav-links ${menuOpen ? 'open' : ''}`}>
            <li><NavLink to="/" onClick={() => setMenuOpen(false)}>Strona główna</NavLink></li>
            <li><NavLink to="/about" onClick={() => setMenuOpen(false)}>O nas</NavLink></li>
            <li><NavLink to="/contact" onClick={() => setMenuOpen(false)}>Kontakt</NavLink></li>
          </ul>
        </nav>
      </header>

      <main className="content">
        <Suspense fallback={<p>Ładowanie...</p>}>
          <Routes>
            <Route path="/" element={<Fade><Home /></Fade>} />
            <Route path="/about" element={<Fade><About /></Fade>} />
            <Route path="/contact" element={<Fade><Contact /></Fade>} />
          </Routes>
        </Suspense>
      </main>
    </div>
  )
}

function Fade({ children }) {
  return <div className="fade">{children}</div>
}

// SPA/spa-router-apps/angular-spa-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet, RouterLink } from '@angular/router';
import { fadeAnimation } from './fade.animation';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink],
  animations: [fadeAnimation],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  menuOpen = false;

  toggleMenu() {
    this.menuOpen = !this.menuOpen;
  }

  closeMenu() {
    this.menuOpen = false;
  }
}

<div id="app">
<header>
  <nav class="navbar">
    <div class="logo">🌐 Moja SPA</div>
    <button class="hamburger" (click)="toggleMenu()">☰</button>
    <ul [class.open]="menuOpen" class="nav-links">
      <li><a routerLink="/" (click)="closeMenu()">Strona główna</a></li>
      <li><a routerLink="/about" (click)="closeMenu()">O nas</a></li>
      <li><a routerLink="/contact" (click)="closeMenu()">Kontakt</a></li>
    </ul>
    
  </nav>
</header>

<main class="content" [@fadeAnimation]>
  <router-outlet></router-outlet>
</main>
</div>
